In [1]:
import h5py
import numpy as np
import pandas as pd

In [2]:
f = h5py.File("/data/whd01/yiyu_data/PNWML/miniPNW/waveforms.hdf5", "r")
f2 = h5py.File("/data/whd01/yiyu_data/PNWML/mesoPNW/waveforms.hdf5", "w")

In [3]:
f2.create_group('data_format')
f2.create_group('data')
f2['data_format']['component_order'] = f['data_format']['component_order'][()]

In [4]:
df = pd.read_csv("/data/whd01/yiyu_data/PNWML/miniPNW/metadata.csv")
df["bucket"] = df.apply(lambda r: int(r.trace_name.split("$")[0][6:]), axis = 1)
df["tindex"] = df.apply(lambda r: int(r.trace_name.split("$")[1].split(",")[0]), axis = 1)

df2 = pd.DataFrame(columns=df.columns)

In [5]:
for bucket in range(1, 11):
    new_index = df[df["bucket"] == bucket].tindex.max()//10
    print(bucket, new_index)
    df2 = pd.concat([df2, df[(df["bucket"] == bucket) & (df["tindex"] < new_index)]])
    
    f2['data'][f"bucket{bucket}"] = f['data'][f"bucket{bucket}"][:new_index, :, :]
df2.sort_index(inplace=True)

1 1878

/tmp/ipykernel_452309/4262165382.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df2 = pd.concat([df2, df[(df["bucket"] == bucket) & (df["tindex"] < new_index)]])

2 1856
3 1854
4 1876
5 1895
6 1849
7 1875
8 1879
9 1874
10 1864

In [7]:
df2.to_csv("/data/whd01/yiyu_data/PNWML/mesoPNW/metadata.csv", index=None)

In [8]:
f.close()
f2.close()

In [9]:
df2

,event_id,source_origin_time,source_latitude_deg,source_longitude_deg,source_type,source_depth_km,preferred_source_magnitude,preferred_source_magnitude_type,preferred_source_magnitude_uncertainty,source_depth_uncertainty_km,...,source_type_pnsn_label,source_local_magnitude,source_local_magnitude_uncertainty,source_duration_magnitude,source_duration_magnitude_uncertainty,source_hand_magnitude,trace_missing_channel,trace_has_offset,bucket,tindex
0,uw10564613,2002-10-03T01:56:49.530000Z,48.553,-122.520,earthquake,14.907,2.10,md,0.030,1.68,...,eq,NaN,NaN,2.10,0.030,NaN,0,1,4,0
1,uw10564613,2002-10-03T01:56:49.530000Z,48.553,-122.520,earthquake,14.907,2.10,md,0.030,1.68,...,eq,NaN,NaN,2.10,0.030,NaN,2,0,9,0
2,uw10564613,2002-10-03T01:56:49.530000Z,48.553,-122.520,earthquake,14.907,2.10,md,0.030,1.68,...,eq,NaN,NaN,2.10,0.030,NaN,0,1,4,1
3,uw10564613,2002-10-03T01:56:49.530000Z,48.553,-122.520,earthquake,14.907,2.10,md,0.030,1.68,...,eq,NaN,NaN,2.10,0.030,NaN,2,0,7,0
4,uw10568748,2002-09-26T07:00:04.860000Z,48.481,-123.133,earthquake,22.748,2.90,md,0.030,0.91,...,eq,NaN,NaN,2.90,0.030,NaN,0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19326,uw10751608,2008-09-17T22:05:19.870000Z,47.523,-121.810,earthquake,23.486,2.70,md,0.030,0.31,...,eq,NaN,NaN,2.70,0.030,NaN,0,0,8,1874
19360,uw10752393,2008-08-20T21:26:52.460000Z,46.675,-121.105,earthquake,-0.072,2.00,md,0.040,0.12,...,eq,NaN,NaN,2.00,0.040,NaN,2,0,8,1875
19377,uw10753338,2008-07-31T05:02:43.130000Z,48.152,-122.748,earthquake,55.880,3.87,ml,0.134,0.62,...,eq,3.87,0.134,3.89,0.246,NaN,0,0,8,1876
19379,uw10753338,2008-07-31T05:02:43.130000Z,48.152,-122.748,earthquake,55.880,3.87,ml,0.134,0.62,...,eq,3.87,0.134,3.89,0.246,NaN,0,0,8,1877
19380,uw10753338,2008-07-31T05:02:43.130000Z,48.152,-122.748,earthquake,55.880,3.87,ml,0.134,0.62,...,eq,3.87,0.134,3.89,0.246,NaN,0,0,8,1878